Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/Sahil/AppData/Local/Programs/Python/Python310/ASSIGNMENT 2 (INPUT) .PY

 Answer 1 

(a)	The length of the given string is : 35
(b)	The string in reverse would be : egaugnal evitisnes esac a si nohtyP
(c)	The new string becomes : a case sensitive
(d)	The replaced substring will be : Python is object oriented language
(e)	The first occurence of the given substring "a" is at index no. = 10
(f)	The inputted strings with no white spaces will be "Pythonisacasesensitivelanguage"


 Answer 2 

Hey, PANKAJ KUMAR Here!
My SID is 21105004
I am from Electronics and Communication Engineering department and my CGPA is 9.2

 Answer 3 

a&b= 8
a|b= 58
a^b= 50
a<<2= 224 and b<<2= 40
a>>2= 14 and b>>4= 0
 
 Answer 4 

Enter the  first number : 67
Enter the second number : 87
Enter the third number : 98
The greatest number is 98

 
 Answer 5 

Enter the string : GHDYDYCUGCnamejhvhibui
Yes


 Answer 6 

Enter the dimensions to check whether triangle possible or not : 4 5 8
Yes

